export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCTS_CATEGORIES_LIST = "PRODUCTS_CATEGORIES_LIST";
export const LOAD_RELATED_ITEMS = 'LOAD_RELATED_ITEMS';
export const SET_RELATED_ITEMS = 'SET_RELATED_ITEMS';